openapi: 3.0.0
info:
  title: Transaction API
  description: API для управления транзакциями.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Локальный сервер
paths:
  /task:
    post:
      summary: Создать новую транзакцию
      requestBody:
        description: Новая транзакция, которую нужно создать
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Транзакция успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '500':
          description: Что-то пошло не так
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          example: 6783e0712376f0399790a7cc
        input:
          type: boolean
          example: true
        dateTime:
          type: number
          example: 1737244800000
        amount:
          type: number
          example: 2000
        comment:
          type: string
          example: comment
        userId:
          type: string
          example: 6783e0712376f0399790a7cc